site/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^posts/', include("posts.urls", namespace='posts')),
    # url(r'^posts/$', "posts.views.post_home"),
    # url(r'^posts/$', "<app_name>.views.<function_name>"),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site/posts/urls.py
from django.conf.urls import url
# from . import views
from .views import (
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
)

urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<id>\d+)/$', post_detail, name='detail'),
    url(r'^(?P<id>\d+)/edit/$', post_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', post_delete, name='del'),


    # url(r'^$', views.post_list),
    # url(r'^create/$', views.post_create),
    # url(r'^detail/$', views.post_detail),
    # url(r'^update/$', views.post_update),
    # url(r'^delete/$', views.post_delete),

    # url(r'^$', "posts.views.post_home"),
    # url(r'^$', "<app_name>.views.<function_name>"),

]

site/posts/models.py
# coding = utf-8
from django.conf import settings

from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save

from django.utils import timezone
from django.utils.text import slugify


# Create your models here.
# MVC - Model View Controller

# Post.objects.all()
class PostManager(models.Manager):
    def my_method(self, *args, **kwargs):  # we overwrite this method all / in views it'll be like this Post.objects.my_method()
        # Post.objects.all() --> super(PostManager, self).all()
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_locations(instance, filename):
    # filebase, extension = filename.split(".")
    return "%s" %(filename)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)  # blank=True, null=True

    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_locations, null=True, blank=True, height_field="height_field", width_field="width_field")  # save width and height our image
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()

    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)

    update = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)  # auto_now - always refresh date

    objects = PostManager()  # you can name variable however (objects - post, my_obj, ) and in views you must to write new name of variable

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", args=[self.id]) #kwargs={"id": self.id})

    class Meta:
        ordering = ["-timestamp", "-update"]


# this function for create another url and we use <slug>
def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def pre_save_post_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
    # slug = slugify(instance.title)
    # # if title is 'Some title 2' --> 'Some-title-2' it's for url good
    # exists = Post.objects.filter(slug=slug).exists()
    # if exists:
    #     slug = "%s-%s" %(slug, instance.id)
    # instance.slug = slug

pre_save.connect(pre_save_post_reciever, sender=Post)

site/posts/forms.py
from django import forms
from .models import *


class PostForm(forms.ModelForm):
    publish = forms.DateField(widget=forms.SelectDateWidget())
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'draft',
            'publish'
        ]

site/posts/views.py
from urllib.parse import quote_plus
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Q
from .forms import PostForm
from .models import Post

# Create your views here.
def post_create(request):
    # you can't get this page if you're not admin
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404()

    # even if user not registered we will raise an error
    if not request.user.is_authenticated():
        raise Http404()

    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        # do something before save the form
        print(form.cleaned_data.get("title"))
        instance.user = request.user
        instance.save()
        # success mesage
        messages.success(request, "Was Created!", extra_tags='created')
        return HttpResponseRedirect(instance.get_absolute_url())

    # if request.method == "POST":
    #     title = request.POST.get("title")
    #     content = request.POST.get("content")
    #     Post.objects.create(title=title, content=content)
    return render(request, "post_form.html", {"form": form, "title": "Create new post here!"})


def post_detail(request, id=None):
    # instance = get_object_or_404(Post, id=24)
    try:
        instance = Post.objects.get(id=id)
    except:
        raise Http404()

    share_text = quote_plus(instance.content)

    context = {
        "obj": instance,
        "title": "Detail",
        "share_text": share_text
    }
    return render(request, "post_detail.html", context)


def post_list(request):
    queryset_list = Post.objects.all()  #.order_by("-timestamp")

    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(Q(title__icontains=query) |
                                            Q(content__icontains=query)
                                            # Q(user__first__name__icontains=query)
                                        ) #.distinct()

    paginator = Paginator(queryset_list, 4) # Show 4 posts per page
    page = request.GET.get('p')

    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context = {
        "object_list": queryset,
        "title": "My posts"
    }
    # if request.user.is_authenticated():
    #     context = {
    #         "title": "My list"
    #     }
    # else:
    #     context = {
    #         "title": "List"
    #     }
    return render(request, "post_list.html", context)


def post_update(request, id=None):
    # you can't get this page if you're not admin
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404()
    post = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        # success message
        messages.success(request, "<a href='#'>Item</a> Was Changed!", extra_tags='my-class')
        return HttpResponseRedirect(post.get_absolute_url())

    context = {
        "form": form,
        "title": "Edit the post here!"
    }

    return render(request, "post_form.html", context)


def post_delete(request, id=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404()
    post = get_object_or_404(Post, id=id)
    post.delete()
    messages.success(request, "Was Deleted")
    return redirect("posts:list")

site/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" type="image/png" href="{% static 'assets/images/ico.png' %}">
    <title>{% block head_title %}My Blog =){% endblock head_title %}</title>

    <!-- Here is styles -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
</head>
<body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/uk_UA/sdk.js#xfbml=1&version=v2.8&appId=148375768953027";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>


    <div class="container">
        <h1>Welcome to Blog</h1>
        {% include "message_display.html" %}

        {% block content %}{% endblock content %}
    </div>

    <!-- <img src="{% static 'img/beach.jpg' %}" alt="no photo"> -->



    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" charset="utf-8"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

site/templates/message_display.html
{% if messages %}
    <!-- it can be what ever just like ul->li div, p, span-->
    <div class="alert alert-success col-sm-6 col-sm-offset-3" role="alert">
        {% for message in messages %}
            <span class="{{ message.tags }}">
                <!-- my-class this is in views -->
                {% if "my-class" in message.tags %}
                    {{ message|safe }}
                {% else %}
                    {{ message }}
                {% endif %}
            </span>
        {% endfor %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    </div>
    <br>
{% endif %}

site/templates/post_detail.html
{% extends "base.html" %}

{% block head_title %}
    {{ obj.title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
        {% if obj.image %}
            <img src="{{ obj.image.url }}" class="img-responsive">
        {% endif %}
        <h1>{{ obj.title }} <small>{{ obj.timestamp }}</small></h1>
        {% if obj.user.get_full_name %}
            <p>Author: {{ obj.user.get_full_name }}</p>
        {% endif %}
        <!-- {{ obj.pk }} <br> -->
        <!-- {{ obj.title }} <br> -->
        <!-- {{ obj.update }} <br> -->

        <!-- {{ request.build_absolute_uri }} -->
        <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="true"></div>
        <!-- <div class="col-sm-12" style="padding: 0">
            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank">Share on Facebook</a> |
            <a href="https://twitter.com/home?status={{ share_text }}%20{{ request.build_absolute_uri }}" target="_blank">Share on Twitter</a> |
            <a href="https://plus.google.com/share?url={{ request.build_absolute_uri }}" target="_blank">Share on Google+</a> |
            <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ obj.title }}&summary={{ share_text }}&source={{ request.build_absolute_uri }}" target="_blank">Share on LinkedIn</a> |
            <a href="https://pinterest.com/pin/create/button/?url={{ request.build_absolute_uri }}&media=&description={{ obj.content }}" target="_blank">Pin on Pinterest</a>
        </div> -->
        <hr>

        <p>{{ obj.content|linebreaks }}</p>

        <div class="row">
            <div class="col-sm-12">
                {% if request.user.is_authenticated and request.user.is_staff %}
                    <a href="{% url 'posts:update' obj.id %}" class="btn btn-warning">Edit</a> or
                    <a href="{% url 'posts:del' obj.id %}" class="btn btn-danger">Delete</a> - <small>{{ obj.title|truncatewords:3 }}</small>
                {% endif %}
                <a href="{% url 'posts:list' %}" class="btn btn-info" style="float:right;">Return to all</a>
            </div>
        </div>

        <br>
        <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>
    </div>

    <!-- urlify -->
    <!-- {{ obj.content }} -->
    <!-- {{ share_text }} -->

{% endblock content %}

site/templates/post_form.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
<!-- exten other information from base.html -->
<!-- {{ block.super }} -->
    <div class="col-sm-6 col-sm-offset-3">
        <h1>{{ title }}</h1>

        <form action="" method="post" class="navbar-form navbar-left" enctype="multipart/form-data">{% csrf_token %}
            <div class="form-group">
                {% for field in form %}
                    <p>
                        <label for="id_{{ field.name }}">{{ field.label }}</label>
                        {% render_field field class="form-control" %}
                    </p>
                    <!-- Below is errors -->
                    {% for error in field.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                {% endfor %}
                <input type="submit" class="btn btn-default" value="Create post">
                <a href="{% url 'posts:list' %}" class="btn btn-warning" style="float:right;">Return to all</a>
            </div>
        </form>
    </div>
{% endblock content %}

site/templates/post_list.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-12">
        <h1>{{ title }}</h1>
    </div>

    <!-- Search field -->
    <div class="row">
        <div class="col-sm-6 col-sm-offset-1">
            <form action="" method="get" class="navbar-form">
                <div class="form-group">
                    <input type="text" name="q" placeholder="Search posts" class="form-control" value="{{ request.GET.q }}">
                    <button type="submit" class="btn btn-info">
                        Let's find
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>
            </form>
        </div>
        <!-- create post -->
        {% if request.user.is_authenticated and request.user.is_staff %}
            <div class="col-sm-2 col-sm-offset-3">
                <a href="{% url 'posts:create' %}" class="btn btn-success">Create new post</a>
            </div>
        {% endif %}
    </div>
    <br>

    <div class="row">
    {% for obj in object_list %}
        <div class="col-sm-6">
            <div class="thumbnail">
                {% if obj.image %}
                    <img src="{{ obj.image.url }}" class="img-responsive">
                {% endif %}
                <div class="caption">
                    <h3>
                        <a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a>
                        <small>{{ obj.timestamp|timesince }} ago</small>
                    </h3>
                    <!-- There is name of user below -->
                    {% if obj.user.get_full_name %}
                        <p>Author: {{ obj.user.get_full_name }}</p>
                    {% endif %}
                    <p>{{ obj.content|linebreaks|truncatechars:120 }}</p>
                    <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
                </div>
            </div>
        </div>

        <!-- cycle "row1" "row2" it's like first and second element -->
        {% cycle "" "<div class='col-sm-12'><hr></div></div><div class='row'>" %}
    {% endfor %}

    </div>

    <div>
        <div class="pagination">
            <ul class="pager">
                <li class="previous">
                    {% if object_list.has_previous %}
                        <a href="?p={{ object_list.previous_page_number }}
                        {% if request.GET.q %}
                            &q={{ request.GET.q }}
                        {% endif %}">&larr; previous</a>
                    {% endif %}
                </li>

                <li class="btn">
                    Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                </li>

                <li class="next">
                    {% if object_list.has_next %}
                        <a href="?p={{ object_list.next_page_number }}
                        {% if request.GET.q %}
                            &q={{ request.GET.q }}
                        {% endif %}">next &rarr;</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
{% endblock content %}